# Generated by Django 2.2.5 on 2019-12-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('unique_squirrel_id', models.CharField(help_text='Unique Squirrel ID Number', max_length=50, primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=10, help_text='Longitude coordinate for squirrel sighting point', max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=10, help_text='Latitude coordinate for squirrel sighting point', max_digits=15)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='Unknown', help_text='Shift in the day', max_length=2)),
                ('date', models.DateField(help_text='Concatenation of the sighting session day and month.')),
                ('age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of squirrel', max_length=16)),
                ('primary_fur_color', models.CharField(choices=[('Cinnamont', 'Cinnamont'), ('Black', 'Black'), ('Gray', 'Gray')], default='Unknown', help_text='Primary Fur Color of squirrel', max_length=16)),
                ('location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane')], default='Unknown', help_text='Location of squirrel', max_length=16)),
                ('specific_location', models.CharField(blank=True, help_text='Specific Location', max_length=255)),
                ('running', models.BooleanField(default=False, help_text='If squirrel is running')),
                ('chasing', models.BooleanField(default=False, help_text='If squirrel is chasing')),
                ('climbing', models.BooleanField(default=False, help_text='If squirrel is climbing')),
                ('eating', models.BooleanField(default=False, help_text='If squirrel is eating.')),
                ('foraging', models.BooleanField(default=False, help_text='If squirrel is foraging.')),
                ('other_activities', models.CharField(blank=True, help_text='Other Activities', max_length=255)),
                ('kuks', models.BooleanField(default=False, help_text='Squirrel was heard kukking.')),
                ('quaas', models.BooleanField(default=False, help_text='Squirrel was heard quaaing.')),
                ('moans', models.BooleanField(default=False, help_text='Squirrel was heard moaning')),
                ('tail_flags', models.BooleanField(default=False, help_text='Squirrel was seen flagging its tail.')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Squirrel was seen twitching its tail. ')),
                ('approaches', models.BooleanField(default=False, help_text='Squirrel was seen approaching human, seeking food.')),
                ('indifferent', models.BooleanField(help_text='Squirrel was indifferent to human presence.')),
                ('runs_from', models.BooleanField(default=False, help_text='Squirrel was running from humans, seeing them as a threat.')),
            ],
        ),
    ]
