# Generated by Django 3.0 on 2019-12-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(help_text='Latitude of Squirrel', max_length=50)),
                ('Longitude', models.FloatField(help_text='Longitude of Squirrel', max_length=50)),
                ('UniqueSquirrelID', models.CharField(help_text='Unique Squirrel ID Number', max_length=50)),
                ('Shift', models.CharField(help_text='Shift in the day', max_length=2)),
                ('Date', models.CharField(help_text='Squirrel Come Date', max_length=2)),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenilee', 'Juvenilee')], help_text='Age of squirrel', max_length=16)),
                ('PrimaryFurColor', models.CharField(choices=[('Cinnamont', 'Cinnamont'), ('Black', 'Black'), ('Gray', 'Gray')], help_text='Primary Fur Color of squirrel', max_length=16)),
                ('Location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane')], help_text='Location of squirrel', max_length=16)),
                ('SpecificLocation', models.CharField(help_text='Specific Location', max_length=100)),
                ('Running', models.BooleanField(help_text='If squirrel is running')),
                ('Chasing', models.BooleanField(help_text='If squirrel is chasing')),
                ('Climbing', models.BooleanField(help_text='If squirrel is climbing')),
                ('Eating', models.BooleanField(help_text='If squirrel is eating')),
                ('Foraging', models.BooleanField(help_text='If squirrel is foraging')),
                ('OtherActivities', models.CharField(help_text='Other Activities', max_length=100)),
                ('Kuks', models.BooleanField(help_text='Kuks')),
                ('Quaas', models.BooleanField(help_text='Quaas')),
                ('Moans', models.BooleanField(help_text='Moans')),
                ('Tailflags', models.BooleanField(help_text='Tail flag')),
                ('Tailtwitches', models.BooleanField(help_text='Tail twitches')),
                ('Approaches', models.BooleanField(help_text='Approachesg')),
                ('Indifferent', models.BooleanField(help_text='Indifferent')),
                ('Runsfrom', models.BooleanField(help_text='Runs fromg')),
            ],
        ),
    ]
